[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    vshymanskyy/TinyGSM @ ^0.11.5
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.3

build_flags =
    -D TINY_GSM_MODEM_SIM900
    -D TINY_GSM_USE_GPRS=true
    -D TINY_GSM_RX_BUFFER=1024
